## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/obophenotype for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

# command to run tests
script: cd src/ontology && make pattern_ontology

branches:
  only:
    - master
    - test-travis

notifications:
  email:
    - nicolas.matentzoglu@gmail.com
    - vasilevs@ohsu.edu