sudo: required

#services:
#  - docker

#before_install:
#  - docker pull obolibrary/odkfull


#jdk:
#  - oraclejdk8


# command to run tests; working directory is not altered for the second set of parentheses
#script:
#  - ./run.sh make test

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis


notifications:
  email:
    - cjmungall@lbl.gov
    - sebastian.koehler@charite.de
    - balhoff@renci.org
