sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/oskfull

# command to run tests; working directory is not altered for the second set of parentheses
script: "(cd src/patterns && make test) && (make test)"

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master

notifications:
  email:
    - cjmungall@lbl.gov
    - sebastian.koehler@charite.de
    - balhoff@renci.org
